### ISSUE TITLE
Add 2021-Sept Public Meeting minutes

### ISSUE THREAD

**Issue by cjfields** [OBF/obf-docs#104]
This was mistakenly merged in and is now reverted, is now on a branch (#92).  I believe we will need to either revert the reversion (:wink) or generate a new pull request to ensure it's included back in.

**Comment by nlharris** [comment]
Can you do whichever you decide on ASAP, so I can add the link to the meeting agenda? Thanks!

**Comment by hlapp** [comment]
Based on what I found online there are two ways:

1. Revert the pull request to revert, which will generate a new pull request.
2. Create a new branch, cherry pick the commits that were part of the original (and prematurely merged) pull request, then create a new pull request from that.

Either way, the new pull request needs to then be approved by a quorum, and after the motion passes at the Board meeting document this fact and merge.

Option 1 can be operated by clicking, but will result in a reversion of a reversion added to the main branch. Option 2 will result in double-attribution of the originally single-authored commits. I don't have a strong opinion on which one is better.

BTW in case someone is wondering, this cannot be done by rebasing the original branch with the changes onto the current state of master, because the changes from the branch have since been reverted, so it results in a noop. Also, re-merging the original branch looks like a very bad idea based on diff, presumably because of the changes that have happened since.

**Comment by nlharris** [comment]
Thanks for the research, Hilmar!

I have no opinion about how this is done. Option 1 sounds like it might be more straightforward. Please someone just do whichever is easiest!

**Comment by cjfields** [comment]
Hi @nlharris @hlapp see #105 , which would effectively add the minutes back once approved.

**Comment by cjfields** [comment]
Also, @nlharris we could use the link to the original pull request (#92) to this as it has the full list of changes.

**Comment by hlapp** [comment]
I think we need to use #105 for the minutes. It should in fact have the exact same change set, not sure @cjfields why you think it wouldn't?

**Comment by cjfields** [comment]
@hlapp I'm fine either way, though much of the discussion re: changes is in the original ticket.

**Comment by hlapp** [comment]
> much of the discussion re: changes is in the original ticket

Good point! That said, I've been assuming that the approval of the minutes will pass with unanimous consent and without discussion. But maybe I'm wrong 🤔😉
