### ISSUE TITLE
OBF/.github archived?

### ISSUE THREAD

**Issue by nlharris** [OBF/obf-docs#111]
I wanted to work on the README for https://github.com/OBF/, but noticed that for some reason https://github.com/OBF/.github says 
> This repository has been archived by the owner before Nov 8, 2022. It is now read-only.

That was pretty recent. What's up with that? I don't remember this being discussed (which doesn't mean it wasn't!).

**Comment by peterjc** [comment]
Confused. I don't even recall that repo existing.

**Comment by hlapp** [comment]
It says it was archived by the owner. There were 3 commits, all by @nlharris. We can unarchive it. Should we?

**Comment by nlharris** [comment]
I guess so? Are you saying I archived it? Who's the owner?

**Comment by hlapp** [comment]
I think in this case this would be the organization, i.e., those with role "Owner" in the organization: https://github.com/orgs/OBF/people?query=role%3Aowner

The more important question is whether this was accidental (in which case we should simply unarchive the repo) or intentional (in which case we should _not_ revert it).

**Comment by hlapp** [comment]
Done.

**Comment by peterjc** [comment]
Thank you

**Comment by peterjc** [comment]
Confirming the text now appears on https://github.com/OBF as our profile
