### ISSUE TITLE
It is unclear whether certain projects have an initial status

### ISSUE THREAD

**Issue by hlapp** [OBF/obf-docs#16]
Initial status?  It is unclear whether certain projects have an initial status (such as BioPerl as a Core OBF Project) or whether all projects start with no status and achieve a status only by voting.  If there is an initial status, I assume it would be based on an existing relationship with OBF.   I would not object to such a system (particularly since the status can be change by later votes), but I think it would be helpful to clarify the initial status intent in the document.

Reported by @longb

**Comment by kcranston** [comment]
I think it is fine to introduce changes to the policy while being explicit that this does not affect existing relationships. I also note that the policy says nothing about how projects lose OBF status, or whether there should be a periodic revisiting of project status. What happens if a project no longer has a significant user / developer community, or no longer participates in OBF activities? Does the list of projects only grow?

**Comment by peterjc** [comment]
Projects like BioCorba, BioDAS, and more recently BioLib have faded away, and could probably be described as of historic interest, which is not to say they are not OBF affiliated anymore but rather their status is moot.

i.e. The active projects list can shrink.

**Comment by hlapp** [comment]
Each of the statuses can be lost, such as by a project becoming inactive. I think the head revision at #44 says this clearly enough?

**Comment by hlapp** [comment]
The change in #57 adds the grandfathering clause. Note that this uses a narrower definition of "original OBF member projects", based more or less of off the projects [listed on the OBF wiki as of July 2019](https://www.open-bio.org/w/index.php?title=Projects&oldid=5228) as "Main Projects".

@peterjc note that this does _not_ include BioCORBA and BioLib, but does include DAS (a.k.a. BioDAS).

I believe #57 does address this issue sufficiently well, so I am closing it. Please comment (and reopen) if you feel something is missing.
