### ISSUE TITLE
What are the requirements for initiating a ballot and ballot entry?

### ISSUE THREAD

**Issue by hlapp** [OBF/obf-docs#20]
Procedural questions related to voting: If any subset of OBF members can initiate a ballot, what are the requirements for the constitution of such a group?  Can someone wanting to promote a particular project ask to join?  (Disclaimer - I do not personally have plans to promote any particular project.)  If the committee is fixed (appointed by OBF officers, for example), is there a mechanism for a non-member to submit a recommendation that a project be balloted?

Reported by @longb.

**Comment by kcranston** [comment]
I have a question about the entire [ballot preparation](https://github.com/OBF/obf-docs/blob/unratified-drafts/Affiliated-Project-Policy.md#ballot-preparation) section. This seems to put all of the work on some to-be-identified group of OBF members, rather than the projects seeking membership. If I were leading a project seeking membership, this document would give me little guidance about how to proceed - who to contact, forms to fill out, etc.

**Comment by hlapp** [comment]
> If I were leading a project seeking membership, this document would give me little guidance about how to proceed - who to contact, forms to fill out, etc.

I agree but I am skeptical that it's a good idea to place spelling this out within the scope of the policy, rather than a separate document that proposes an (initial, or subsequently improved) implementation.

**Comment by hlapp** [comment]
There's now a description about [how to initiate an application](https://github.com/OBF/obf-docs/blob/affiliated-projects-policy/Affiliated-project-FAQ.md#q-how-do-i-apply-for-obf-affiliated-project-status) in the corresponding FAQ. Does this suffice to address the issue/question?

**Comment by yochannah** [comment]
I think this is sufficient for now, and the ballot process can be handled either by the board or by a nominated sub-committee. Committee (rather than individual) needed because the likelihood is we may be conflicted since many of us are involved with bio* projects.

**Comment by hlapp** [comment]
Deemed sufficiently addressed for now.
