### ISSUE TITLE
state what membership means

### ISSUE THREAD

**Issue by agarwal** [OBF/obf-docs#23]
I'm unclear on the difference between Core and Affiliated projects. Core projects are defined as being more active, but what practical consequence does this distinction have?

It might help to describe what being an OBF member means in terms of:
- what you get and 
- what you are expected to give.

So far I can tell that what you get is: server resources and publicity. And what you are expected to give is: some volunteer time, but I'm unsure if it's really required.

**Comment by peterjc** [comment]
I presume this is regard to  #14?

**Comment by mr-c** [comment]
I agree that the policy should be explicit about the benefits and responsibilities.

Specifically, does this include fiscal sponsorship and asset ownership? I think it does, and that is what the CWL community is seeking. 

Examples of services offered by similar organizations:

NumFocus: (just fiscal sponsorship, or full project ownership: donations via check, PayPal, Dwolla and Bitcoin; employment or hiring of contractors on behalf of the project; asset ownership (trademarks, domain names, etcetera)) http://www.numfocus.org/information-on-fiscal-sponsorship.html

SPI services offered to affiliated projects (accepting money, holding funds, disbursements,  holding substantial assets, holding intangible assets, signing contracts, legal assistance, technical assistance) http://www.spi-inc.org/projects/services/

Software Freedom Conservancy services offered: https://sfconservancy.org/members/services/

**Comment by peterjc** [comment]
The OBF is itself currently an SPI affiliated project, and they hold our main financial assets. Additionally we have a escrow account with the ISCB for running the annual BOSC meeting. As far as I know (and I am a board member), the OBF does not currently have any project-specific earmarked funds (e.g. X dollars earmarked for BioJava).

The OBF manages the domain names of most (if not all) of the OBF member projects (and covers their renewal costs from our funds). We are exploring moving this to the SPI.

**Comment by mr-c** [comment]
@peterjc Thanks for the information. Would OBF be willing to pass through some of the services it is eligible for from SPI?

**Comment by peterjc** [comment]
I believe the OBF member projects can benefit from access to the SPI services via the OBF, but in practise other than domain names, I can only think of one practical example of OBF projects using the SPI services:

Biopython asked the SPI (via the OBF board) for legal advice about changing the Biopython license, where the SPI put us in touch with the Software Freedom Law Center https://www.softwarefreedom.org/

**Comment by mr-c** [comment]
@peterjc So member projects aren't collecting funds and spending them to support their work? That is a major need for the CWL project.

**Comment by peterjc** [comment]
@mr-c Yes, to my knowledge thus far none of the OBF projects have individually collected funds and spent them to support their work. This has only been at a group level (e.g. The money raised from GSoC going to the general coffers, being spent on domain names and server costs etc).

It sounds like right now if CWL fund raising to support ongoing work is going to be a major activity, you would be better off joining a financial sponsorship (or even forming its own non-profit).

[This thread has been useful in terms of the original issue - defining what exactly being an OBF member project means, so thank you for raising this]

**Comment by mr-c** [comment]
Thank you @peterjc, it is good to have this clarified. Yes, we have contacted SPI and others. From what I've been told forming a non profit with less than 2 000 000 USD / year in revenue is inefficient so until we have that "opportunity" we are looking for a fiscal sponsor.

**Comment by hlapp** [comment]
So just to be clear, OBF is not currently a fiscal sponsorship organization. We have discussed in the past the possibility of becoming our own 501(c)3 to act as one, but so far we have deliberately chosen not to. We very well recognize that there is a need for a fiscal sponsorship organization in the bioinformatics space. However, at this point it's not clear what particular needs in this regard aren't or can't be filled by the fiscal sponsorship organizations that exist and are relevant for this space, in particular NumFOCUS, SPI, and the SF Conservancy. 

We do, by the nature of OBF as an umbrella organization for its member projects, pass through all benefits that come from being an SPI affiliated project. But we didn't become an SPI affiliated project so we can be a fiscal sponsor in disguise, or to save our member projects from having to apply themselves to a fiscal sponsor if a fiscal sponsor were what they are most looking for. OBF is first and foremost a community.  The OBF Board acts on behalf of our community. This includes liaising with a fiscal sponsor and as a result making the sponsor's services available to all members of our community. But we are not, nor aspire to be, a broker between a project seeking fiscal sponsorship and a fiscal sponsor. Speaking personally, I don't think there is a demonstrated need for, or benefit from having such a broker. 

If an OBF project raises funds collected by SPI, they do so as part of our community. If we disburse funds from our assets held at SPI, we do so consistent with our mission and for the benefit of our community as a whole. Project-specific expenditures of funds will usually meet those criteria by the very nature of what our projects are and do, but this is not a foregone conclusion and ultimate judgment and authority rests with the OBF Board, not the individual member project.

This is quite different from a fiscal sponsor, which normally only assumes oversight over ensuring that expenses meet applicable non-profit tax and other laws (because that's what a fiscal sponsor is accountable for to the IRS).

**Comment by kcranston** [comment]
Going back to the original question, I agree that the proposal needs to be much clearer on the difference between the various types of projects. As it stands, the only difference between *Core* and *Affiliated* is the user base: "established sizable bioinformatics " vs "limited or small". This is both hard to quantify, but also says nothing about what the project gives to OBF or receives from OBF.

**Comment by hlapp** [comment]
Is this better now in #44? I think the main difference is that _Core OBF Project_ is primarily for grandfathering the Bio* projects.

It is debatable whether there is any value in having a separate category for the Bio* projects and other projects like them (large community, very widely used, been around for many years). Opinions one way or another welcome.

**Comment by yochannah** [comment]
I feel that member project and candidate project affiliation statuses are meaningful, but I'm not sure that having core vs affiliated is terribly necessary - e.g. you're simply either a member or not a member. This seems clearer to me but I do not feel strongly about this.

**Comment by gedankenstuecke** [comment]
I agree with @yochannah on this, the `project` and `candidate` status difference makes sense, the core/affiliated should be obsolete at least on the long run.

**Comment by hlapp** [comment]
It seems to me that this first started, and later converged again on the question what distinguishes Core from Affiliated OBF Projects. Given that the Core OBF Project tier has now been eliminated (see #55), this question should now be moot.

There is also, spawned from the initial question, some discussion here as to what benefits OBF member projects (as an Affiliated, and possibly even as Candidate OBF Project) are eligible to receive. This is a good point that this can and needs to be better documented. But I argue that _this_ (the Affiliated Projects) policy isn't the right place for it, as it should concern itself _only_ with the process of attaining and losing OBF affiliation. (I.e., this policy should not have to change when the services the OBF and by extension its member projects have access to change.)

**Comment by hlapp** [comment]
I've now moved the parts of the thread that are about documenting services available (in particular those  relating to fiscsal sponsorship) into its own issue (#58). I believe with that we can close this issue. Comment and reopen the issue if you feel differently.
